package system;

/**
 * Created by billy on 6/28/17.
 */
public interface SystemConstants
{
    int DEFAULT_CANVAS_WIDTH = 1250;
    int DEFAULT_CANVAS_HEIGHT = 1250/16*9;

    int PASSABLE = 0;
    int NONPASSABLE = 1;

    int EAST = 0;
    int NORTHEAST = 1;
    int NORTH = 2;
    int NORTHWEST = 3;
    int WEST = 4;
    int SOUTHWEST = 5;
    int SOUTH = 6;
    int SOUTHEAST = 7;

    int IMAGE_TILE_GRASS1 = 0;
    int IMAGE_ENTITY_TEST = 1;
    int IMAGE_TREE = 2;
    int IMAGE_TILE_WATER = 3;
    int IMAGE_MOUNTAIN = 4;
    int IMAGE_MAGECITY = 5;
    int IMAGE_TILESELECT = 6;
    int IMAGE_SIMPLEWALLS = 7;
    int IMAGE_HUGECOLLECTION1 = 8; //64x48

    int SHEET_HUGECOLLECTION1 = 0;
    int SHEET_MAGECITY = 1;
    int SHEET_TOPWALLS = 2;

    int NO_RENDER_COLOR = 0xFFFF69B4;

    int SPRITE_GRASS1 = 0;

    int SPRITE_GRASS_PLAIN = 1000;
    int SPRITE_COBBLE_WALK_PLAIN1 = 1001;
    int SPRITE_LAYER_LONGGRASS = 1002;
    int SPRITE_LAYER_SMALLGRASS = 1003;
    int SPRITE_BLANK_GREY = 1008;

    int SPRITE_WALL_BRICK_PLAIN1 = 1033;
    int SPRITE_WALL_BRICK_TOP = 1036;
    int SPRITE_WALL_BRICK_DARK = 1041;

    int SPRITE_COBBLE_WALK_PLAIN2 = 1081;
    int SPRITE_ROOF_BACKLEFT = 1184;
    int SPRITE_ROOF_BACK = 1185;
    int SPRITE_ROOF_BACKRIGHT = 1186;
    int SPRITE_ROOF_LEFT = 1192;
    int SPRITE_ROOF_MIDDLE = 1193;
    int SPRITE_ROOF_RIGHT = 1194;
    int SPRITE_ROOF_LEFTCORNER = 1195;
    int SPRITE_ROOF_RIGHTCORNER = 1196;
    int SPRITE_ROOF_FRONTLEFT = 1200;
    int SPRITE_ROOF_FRONT = 1201;
    int SPRITE_ROOF_FRONTRIGHT = 1202;
    int SPRITE_WALL_BRICK_TOP2 = 1213;
    int SPRITE_WALL_BRICK = 1221;

    int SPRITE_WALL_TOPBACK = 2000;
    int SPRITE_WALL_TOPLEFT = 2001;
    int SPRITE_WALL_TOPFRONT = 2002;
    int SPRITE_WALL_TOPRIGHT = 2003;
    int SPRITE_WALL_TOPFRONTLEFT = 2004;
    int SPRITE_WALL_TOPBACKLEFT = 2005;
    int SPRITE_WALL_TOPBACKRIGHT = 2006;
    int SPRITE_WALL_TOPFRONTRIGHT = 2007;
    int SPRITE_BLACK = 2008;
    int SPRITE_WALL_TOPINNERBACKLEFT = 2009;
    int SPRITE_WALL_TOPINNERBACKRIGHT = 2010;
    int SPRITE_WALL_TOPINNERFRONTLEFT = 2011;
    int SPRITE_WALL_TOPINNERFRONTRIGHT = 2012;

    int SPRITE_HUGECOLLECTION_FLOOR_COBBLE1 = 6809;
    //x:9y:1 to x:63y:5 monsters;
    int SPRITE_HUGECOLLECTION_STARTMONSTERBATCH = 6073;
    int SPRITE_HUGECOLLECTION_ENDMONSTERBATCH = 6383;

    //attributes
    int ATTRIBUTE_LISTSIZE = 59;
    int ATTRIBUTE_HITPOINTS = 0;
    int ATTRIBUTE_HITPOINTS_CURRENT = 1;
    int ATTRIBUTE_MANAPOINTS = 2;
    int ATTRIBUTE_MANAPOINTS_CURRENT = 3;
    int ATTRIBUTE_STAMINA = 4;
    int ATTRIBUTE_STRENGTH = 5;
    int ATTRIBUTE_DEXTERITY = 6;
    int ATTRIBUTE_INTELLIGENCE = 7;
    int ATTRIBUTE_ENDURANCE = 8;
    int ATTRIBUTE_FAITH = 9;
    int ATTRIBUTE_ATTUNEMENT = 10;
    int ATTRIBUTE_LUCK = 11;
    int ATTRIBUTE_DEFENCE_PHYSICAL = 12;
    int ATTRIBUTE_DEFENCE_MAGIC = 13;
    int ATTRIBUTE_ATTACK_PHYSICAL = 14;
    int ATTRIBUTE_ATTACK_MAGIC = 15;
    int ATTRIBUTE_ATTACK_SPEED = 16;
    int ATTRIBUTE_ATTACK_RANGE = 17;
    int ATTRIBUTE_ATTACK_TYPE = 18;
    int ATTRIBUTE_ATTACK_ELEMENT = 19;
    int ATTRIBUTE_ATTACK_FIRE = 20;
    int ATTRIBUTE_ATTACK_LIGHTNING = 21;
    int ATTRIBUTE_ATTACK_ICE = 22;
    int ATTRIBUTE_ATTACK_POISON = 23;
    int ATTRIBUTE_ATTACK_CURSE = 24;
    int ATTRIBUTE_ATTACK_BLEED = 25;
    int ATTRIBUTE_ATTACK_TOXIC = 26;
    int ATTRIBUTE_ATTACK_LIGHT = 27;
    int ATTRIBUTE_ATTACK_DARK = 28;
    int ATTRIBUTE_ATTACK_HOLY = 29;
    int ATTRIBUTE_DEFENCE_FIRE = 30;
    int ATTRIBUTE_DEFENCE_LIGHTNING = 31;
    int ATTRIBUTE_DEFENCE_ICE = 32;
    int ATTRIBUTE_DEFENCE_POISON = 33;
    int ATTRIBUTE_DEFENCE_CURSE = 34;
    int ATTRIBUTE_DEFENCE_BLEED = 35;
    int ATTRIBUTE_DEFENCE_TOXIC = 36;
    int ATTRIBUTE_DEFENCE_LIGHT = 37;
    int ATTRIBUTE_DEFENCE_DARK = 38;
    int ATTRIBUTE_DEFENCE_HOLY = 39;
    int ATTRIBUTE_ATTACK_SLASH = 40;
    int ATTRIBUTE_ATTACK_BLUNT = 41;
    int ATTRIBUTE_ATTACK_STAB = 42;
    int ATTRIBUTE_DEFENCE_SLASH = 43;
    int ATTRIBUTE_DEFENCE_BLUNT = 44;
    int ATTRIBUTE_DEFENCE_STAB = 45;
    int ATTRIBUTE_MAGICFIND = 46;
    int ATTRIBUTE_ITEMFIND = 47;
    int ATTRIBUTE_DODGECHANCE = 48;
    int ATTRIBUTE_AGILITY = 49;
    int ATTRIBUTE_EQUIP_WEIGHT = 50;
    int ATTRIBUTE_EQUIP_WEIGHT_CURRENT = 51;
    int ATTRIBUTE_EQUIP_SLOTS = 52;
    int ATTRIBUTE_EQUIP_SLOTS_CURRENT = 53;
    int ATTRIBUTE_ITEM_WEIGHT = 54;
    int ATTRIBUTE_ITEM_WEIGHT_CURRENT = 55;
    int ATTRIBUTE_ITEM_SLOTS = 56;
    int ATTRIBUTE_ITEM_SLOTS_CURRENT = 57;
    int ATTRIBUTE_SPEED = 58;

}
